export const VIETNAM_BANKS = [
  { code: 'MB', name: 'MB BANK', fullName: 'MB BANK (Ngân hàng Quân Đội)' },
  { code: 'VCB', name: 'Vietcombank', fullName: 'Vietcombank (Ngân hàng Ngoại Thương)' },
  { code: 'CTG', name: 'VietinBank', fullName: 'VietinBank (Ngân hàng Công Thương)' },
  { code: 'BIDV', name: 'BIDV', fullName: 'BIDV (Ngân hàng Đầu tư và Phát triển)' },
  { code: 'TCB', name: 'Techcombank', fullName: 'Techcombank (Ngân hàng Kỹ Thương)' },
  { code: 'VPB', name: 'VPBank', fullName: 'VPBank (Ngân hàng Việt Nam Thịnh Vượng)' },
  { code: 'ACB', name: 'ACB', fullName: 'ACB (Ngân hàng Á Châu)' },
  { code: 'TPB', name: 'TPBank', fullName: 'TPBank (Ngân hàng Tiên Phong)' },
  { code: 'STB', name: 'Sacombank', fullName: 'Sacombank (Ngân hàng Sài Gòn Thương Tín)' },
  { code: 'VIB', name: 'VIB', fullName: 'VIB (Ngân hàng Quốc Tế)' },
  { code: 'HDB', name: 'HDBank', fullName: 'HDBank (Ngân hàng Phát triển TP.HCM)' },
  { code: 'MSB', name: 'MSB', fullName: 'MSB (Ngân hàng Hàng Hải)' },
  { code: 'OCB', name: 'OCB', fullName: 'OCB (Ngân hàng Phương Đông)' },
  { code: 'SHB', name: 'SHB', fullName: 'SHB (Ngân hàng Sài Gòn - Hà Nội)' },
  { code: 'EIB', name: 'Eximbank', fullName: 'Eximbank (Ngân hàng Xuất Nhập Khẩu)' },
  { code: 'LPB', name: 'LPBank', fullName: 'LPBank (Ngân hàng Lộc Phát Việt Nam)' },
  { code: 'Agribank', name: 'Agribank', fullName: 'Agribank (Ngân hàng Nông nghiệp)' },
  { code: 'ABB', name: 'ABBANK', fullName: 'ABBANK (Ngân hàng An Bình)' },
  { code: 'BAB', name: 'Bac A Bank', fullName: 'Bac A Bank (Ngân hàng Bắc Á)' },
  { code: 'NAB', name: 'Nam A Bank', fullName: 'Nam A Bank (Ngân hàng Nam Á)' },
  { code: 'VAB', name: 'VietABank', fullName: 'VietABank (Ngân hàng Việt Á)' },
  { code: 'NCB', name: 'NCB', fullName: 'NCB (Ngân hàng Quốc Dân)' },
  { code: 'VIETBANK', name: 'VietBank', fullName: 'VietBank (Ngân hàng Việt Nam Thương Tín)' },
  { code: 'BVB', name: 'BaoVietBank', fullName: 'BaoVietBank (Ngân hàng Bảo Việt)' },
];
